{% set name = "Flask-Turbolinks" %}
{% set version = "0.2.0" %}

package:
  version: '{{ version }}'
  name: '{{ name|lower }}'

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '9086fa5d425db3530efe7eb96d90067f0531158864f0e7130846e534069d6381'

build:
  noarch: python
  script: python setup.py install  --single-version-externally-managed --record=record.txt
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - flask

test:
  requires:
    - python {{ python_min }}
  imports:
    - flask_turbolinks

about:
  doc_url: https://github.com/lepture/flask-turbolinks
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  home: https://github.com/lepture/flask-turbolinks
  dev_url: https://github.com/lepture/flask-turbolinks
  summary: Turbolinks for Flask.
  description: Turbolinks makes following links in your web application faster.

extra:
  recipe-maintainers:
    - jenzopr
